[build]
  command = "echo 'No build required'"
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/"
  to = "/membership.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-memberships.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/membership.html"
  status = 404