[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  publish = "."

# Ajouter le plugin d'injection
[[plugins]]
package = "netlify-plugin-inline-env"
  [plugins.inputs]
  verbose = "true"  # Pour voir ce qui est inject√© dans les logs

[[redirects]]
  from = "/"
  to = "/membership.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-memberships.html"
  status = 200

[[redirects]]
  from = "/admin-memberships"
  to = "/admin-memberships.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/membership.html"
  status = 404